# Enforce Node and pnpm versions specified in `engines` field of `package.json`
engineStrict: true

# Use whichever pnpm version is available in the environment
pmOnFail: ignore

# Manage peer dependencies explicitly and predictibly
strictPeerDependencies: true
dedupePeerDependents: false

# Approve specific build scripts
allowBuilds:
  esbuild: true

# Relax minimum release age protection for owned packages
minimumReleaseAgeExclude:
  - '@h5web/*'
  - '@esrf/eslint-config'

# Save exact dependency versions in `package.json`
savePrefix: ''
