name: Lint & Build

on:
  pull_request: # for PRs from forks
  push: # to start jobs asap when pushing a branch to open a PR

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v6

      - name: Install ⚙️
        uses: ./.github/actions/install

      - name: Lint 🤓
        run: pnpm lint

  build:
    runs-on: ubuntu-latest
    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v6

      - name: Install ⚙️
        uses: ./.github/actions/install

      - name: Build 👓
        run: pnpm build
